name: release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 11 * * 1'
env:
  CACHE_IAMGE_TAG: cat:${{ github.sha }}
  CACHE_IAMGE_NAME: cat_${{ github.sha }}.tar
jobs:
  build:
    permissions:
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Tests
        run: mvn test
      - name: Build with Mavn
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.CACHE_IAMGE_TAG }}
          outputs: type=docker,dest=${{ env.CACHE_IAMGE_NAME }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ env.CACHE_IAMGE_NAME }}
  security:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Security
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
      - name: Load image
        run: |
          docker load --input artifacts/${{ env.CACHE_IAMGE_NAME }}
      - uses: actions/checkout@v3
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.CACHE_IAMGE_TAG }}
          args: --file=Dockerfile
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
